-- migration_ai_dev.sql — AI Dev Console: projects, dev jobs, AI sessions
CREATE TABLE IF NOT EXISTS dev_projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL DEFAULT '',
  root_path VARCHAR(500) NOT NULL DEFAULT '',
  default_branch VARCHAR(80) NOT NULL DEFAULT 'master',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  opencode_config TEXT NULL,
  test_commands TEXT NULL,
  lint_commands TEXT NULL,
  build_commands TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_dev_project_root (root_path(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dev_jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_code VARCHAR(20) NOT NULL DEFAULT '',
  project_id INT NOT NULL DEFAULT 0,
  request TEXT NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'TELEGRAM',
  requested_by VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(15) NOT NULL DEFAULT 'QUEUED',
  opencode_session_id VARCHAR(64) NULL,
  base_branch VARCHAR(80) NOT NULL DEFAULT '',
  base_commit VARCHAR(80) NOT NULL DEFAULT '',
  work_branch VARCHAR(120) NOT NULL DEFAULT '',
  worktree_path VARCHAR(500) NOT NULL DEFAULT '',
  plan_text MEDIUMTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  summary TEXT NULL,
  files_changed INT NOT NULL DEFAULT 0,
  lines_added INT NOT NULL DEFAULT 0,
  lines_removed INT NOT NULL DEFAULT 0,
  test_status VARCHAR(20) NOT NULL DEFAULT '',
  test_report TEXT NULL,
  review_status VARCHAR(20) NOT NULL DEFAULT '',
  reviewed_by VARCHAR(64) NOT NULL DEFAULT '',
  apply_status VARCHAR(20) NOT NULL DEFAULT '',
  applied_commit VARCHAR(80) NOT NULL DEFAULT '',
  snapshot_id VARCHAR(64) NOT NULL DEFAULT '',
  has_db_migration TINYINT(1) NOT NULL DEFAULT 0,
  has_dependency_change TINYINT(1) NOT NULL DEFAULT 0,
  high_risk_flags VARCHAR(255) NOT NULL DEFAULT '',
  error VARCHAR(500) NULL,
  UNIQUE KEY uq_dev_job_code (job_code),
  KEY idx_dev_jobs_status (status, created_at),
  KEY idx_dev_jobs_session (opencode_session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id VARCHAR(64) NOT NULL DEFAULT '',
  project_id INT NOT NULL DEFAULT 0,
  dev_job_id INT NULL,
  purpose VARCHAR(20) NOT NULL DEFAULT 'QA',
  title VARCHAR(190) NOT NULL DEFAULT '',
  model VARCHAR(80) NOT NULL DEFAULT '',
  status VARCHAR(15) NOT NULL DEFAULT 'ACTIVE',
  tokens_input INT NOT NULL DEFAULT 0,
  tokens_output INT NOT NULL DEFAULT 0,
  cost DOUBLE NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_ai_session (session_id),
  KEY idx_ai_sessions_job (dev_job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
